//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluMarketProgrami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public int Id { get; set; }
        public Nullable<double> KartKomisyon { get; set; }
        public Nullable<bool> Yazici { get; set; }
        public string AdSoyad { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string FirmaAd { get; set; }
    }
}
