//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluMarketProgrami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> KullaniciKod { get; set; }
        public string Sifre { get; set; }
        public Nullable<bool> Satis { get; set; }
        public Nullable<bool> GenelRapor { get; set; }
        public Nullable<bool> StokTakibi { get; set; }
        public Nullable<bool> UrunGiris { get; set; }
        public Nullable<bool> Ayarlar { get; set; }
        public Nullable<bool> FiyatGuncelle { get; set; }
        public Nullable<bool> Yedekleme { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Veresiye { get; set; }
        public Nullable<bool> KullaniciAyarlari { get; set; }
    }
}
