//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluMarketProgrami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veresiye
    {
        public int Id { get; set; }
        public Nullable<int> IslemNo { get; set; }
        public Nullable<bool> Odeme { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<System.DateTime> AlinmaTarih { get; set; }
        public Nullable<System.DateTime> VerilmeTarih { get; set; }
        public Nullable<double> Tutar { get; set; }
    }
}
